sudo: required
services:
  - docker

# For now while I debug the erros
warnings_are_errors:  false

before_deploy:
    # Set up git user name and tag this commit
  - git config --local user.name "$GITHUB_USER"
  - git config --local user.email "GITHUB_MAIL"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

script:
  - 'make image'

deploy:
  - provider: releases
    api_key:
      secure: IVYgotHm8aUX7GwdMytRG01wfh4M+xVFPiOoA3HcGZ+pgicXO5km5w+JmWHzx+tbsj3hMvtdTwXnSQ1gbAwxKviFiHCxk3vKTHsHajqY2oHF4MZjD3vIA8C54iQZeMbizOZMCuwXU6iOrz5aKESvbF2Snc6prkD+im1pDYOQVUemL2ems23Hbtq27meooVL8ULP1hyLnuiikdNQuzooGkFcYPcdIkZCB7Aswx+6M6BjBtO2cpF/W3sHPnUtOnVt9AOAdnRur1vkkroFLOo6G/Qv5Hyts0p/5CHABKaiechBYT2gMo9ys8PecfUwlee2k+AWdMbdiYMn0tyC3DWC4gVY6sOw+WJ46XL5Spl8rAtMnQf0fwdGh6mOKSJE55Tnuu+wgfmPeyCZv0dg4pnMNV92hdbKhLnqfs0CbzIum8m92l+aKuwXysYR+gTsB7hZTSsTsqSiIqxHpopk4MO93PTuyT+/tH4c9n479gw2Wp9YAD+mjGrgDnXVyccZgK8oarlmTHrFnaWSkeoXUahaC262Z4WR+oRxTy4FkleBezkvd6yv+flQJtAP8iYzdQZs7CUQt5mZiuys/a2A+FFYwiA6Chdo60nzTbxv8CFGRmiqW299Wl9JSueaO3JFff8bDj6ko+u3vc2q2K2Lej3V3Fk3Me0vVlcA/AnnF+uGcUkQ=
    file: index/_book/thesis.pdf
    skip_cleanup: true
    draft: true
    overwrite: true
  - provider: script
    script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && make push-image
    on:
      branch: master
